### PR TITLE
Add cosine dist

### PR DESCRIPTION
**Pull request by jandremarais**
First attempt to add cosine distance metric as mentioned in #136

### CODE REVIEW

**Comment by edgarriba** [comment]
@jandremarais thanks for the implementation. I'm considering wether this should be implemented more in terms of Tensor instead of Image. Which brings the question about how we set the axis direction where to compute the metric. What do you think ?

**Comment by jandremarais** [comment]
I see. That makes more sense. Then it probably needs a "dim" parameter in the function too. Should it support broadcasting?

I found these implementation notes in the pytorch source interesting and leaving it here for reference:

https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/Distance.cpp#L274-L303

**Comment by edgarriba** [comment]
i see, maybe we need even first a proper `norm` operator. Which I've been recently thinking about having a separated `kornia-core-ops` crate to disentagle the tensor memory and layout management to the rest of all the operators (even the existing ones). That was actually one of multiple reasons why decided to drop ndarray support to have a clean separated Tensor struct for the mere purpose of moving data round.

**Comment by jandremarais** [comment]
Closing reasons:
- Cosine sim should operate on tensors not images. 
- Cosine sim needs vector norm operation
- Unsure where tensor operations should live

**Comment by jandremarais** [comment]
Closing reasons:

- Cosine sim should operate on tensors not images.
- Cosine sim needs vector norm operation
- Unsure where tensor operations should live

**Comment by edgarriba** [comment]
> Unsure where tensor operations should live

feel free to open a PR creating a new subcrate `kornia-core-ops` in the workspace

**Pull request closed without merging**
