### PR TITLE
Getting started README Fix

### LINKED ISSUE #159: `Getting Started` Not Working Properly
In `Getting Started` Section of README  `cargo run --bin hello_world` throws an error like 

> Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.36s
Running `target/debug/hello_world`
error: the following required arguments were not provided:
  --image-path <IMAGE_PATH>
> Usage: hello_world --image-path <IMAGE_PATH>
> 
> For more information, try '--help'.

It was fixed by `cargo run --bin hello_world -- --image-path tests/data/dog.jpeg`

### PR DESCRIPTION
**Pull request by jeffin07**
Fixed #159 

Error when trying `Getting Started` command `cargo run --bin hello_world`

### CODE REVIEW

**Review by edgarriba — APPROVED** [review]

**Comment by edgarriba** [comment]
thanks so much !

**Comment by jeffin07** [comment]
Hi @edgarriba, CI have 2 failures
1. `Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c cargo build --release"`
2. `error[E0599]: no variant or associated item named `Bfloat16` found for enum `TensorElementType` in the current scope`

Is this a known issue? I have only Updated readme. Is there anything required from my end to fix this ?

**Comment by edgarriba** [comment]
@jeffin07 yep, not sure what is it but defenitely something is trying to pull `ort-2.0.0-rc8` which seems to be broken. The only place this should happen is here https://github.com/kornia/kornia-rs/blob/main/examples/onnx/Cargo.toml#L18 and as you see the version doesn't match at all.

**Comment by edgarriba** [comment]
In any case, we can merge this PR -- and investigate what's causing the other failure.

**Pull request merged**
